"""add uin echo_address keypair to users

Revision ID: 246243d7231a
Revises: 974e9f3ee338
Create Date: 2026-04-19 15:42:39.497707
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246243d7231a'
down_revision: Union[str, None] = '974e9f3ee338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uin', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('echo_address', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('pubkey', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('privkey_encrypted', sa.LargeBinary(), nullable=True))
    op.create_unique_constraint(None, 'users', ['echo_address'])
    op.create_unique_constraint(None, 'users', ['uin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'privkey_encrypted')
    op.drop_column('users', 'pubkey')
    op.drop_column('users', 'echo_address')
    op.drop_column('users', 'uin')
    # ### end Alembic commands ###
