"""initial schema

Revision ID: 974e9f3ee338
Revises: 
Create Date: 2026-04-17 19:23:22.129200
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '974e9f3ee338'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prop_catalog',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('data_type', sa.Enum('string', 'string_array', 'float_', 'int_', 'boolean', 'json', name='propdatatype'), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ask_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('visitor_id', sa.String(length=128), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('belief_refs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['ask_interactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('original_position', sa.Text(), nullable=False),
    sa.Column('current_position', sa.Text(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('echo_mood_at_drift', sa.String(length=128), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('echo_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('style_fingerprint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('belief_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('knowledge_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('voice_prompt', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ingest_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('linkedin_messages', 'linkedin_endorsements', 'linkedin_connections', 'career_history', 'writing_sample', 'voice_declaration', name='sourcetype'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='ingeststatus'), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'published', 'archived', name='entrystatus'), nullable=False),
    sa.Column('security', sa.Enum('public', 'private', 'selected', name='entrysecurity'), nullable=False),
    sa.Column('generated_by', sa.Enum('echo', 'user', 'hybrid', name='generatedby'), nullable=False),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('pub_year', sa.Integer(), nullable=True),
    sa.Column('pub_month', sa.Integer(), nullable=True),
    sa.Column('pub_day', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theme_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('css_overrides', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Enum('ai', 'user', 'template', name='themegeneratedby'), nullable=False),
    sa.Column('base_template', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('visitor_id', sa.String(length=128), nullable=False),
    sa.Column('author_name', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'hidden', 'deleted', name='commentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_entry_id'), 'comments', ['entry_id'], unique=False)
    op.create_table('entry_props',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('prop_key', sa.String(length=64), nullable=False),
    sa.Column('prop_value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['prop_key'], ['prop_catalog.key'], ),
    sa.PrimaryKeyConstraint('entry_id', 'prop_key')
    )
    op.create_table('journal_content',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_content')
    op.drop_table('entry_props')
    op.drop_index(op.f('ix_comments_entry_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('theme_configs')
    op.drop_table('journal_entries')
    op.drop_table('ingest_sources')
    op.drop_table('echo_profiles')
    op.drop_table('drift_events')
    op.drop_table('ask_interactions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('prop_catalog')
    # ### end Alembic commands ###
