"""add exchange tables

Revision ID: ff8c76a8ea42
Revises: 246243d7231a
Create Date: 2026-04-19 15:51:30.798920
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff8c76a8ea42'
down_revision: Union[str, None] = '246243d7231a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guestbook_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('echo_address', sa.String(length=256), nullable=False),
    sa.Column('from_address', sa.String(length=256), nullable=False),
    sa.Column('from_name', sa.String(length=256), nullable=False),
    sa.Column('body', sa.String(length=280), nullable=False),
    sa.Column('from_mood', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guestbook_entries_echo_address'), 'guestbook_entries', ['echo_address'], unique=False)
    op.create_table('letters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_address', sa.String(length=256), nullable=False),
    sa.Column('to_address', sa.String(length=256), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('transport', sa.Enum('web', 'email', 'a2a', 'future', name='lettertransport'), nullable=False),
    sa.Column('thread_root_id', sa.Uuid(), nullable=True),
    sa.Column('in_reply_to_id', sa.Uuid(), nullable=True),
    sa.Column('ghost_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sender_mood', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['in_reply_to_id'], ['letters.id'], ),
    sa.ForeignKeyConstraint(['thread_root_id'], ['letters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letters_to_address'), 'letters', ['to_address'], unique=False)
    op.create_table('ghost_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incoming_letter_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('draft_body', sa.Text(), nullable=False),
    sa.Column('generated_envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'edited_and_sent', 'rejected', 'expired', name='ghostdraftstatus'), nullable=False),
    sa.Column('holder_decision_at', sa.DateTime(), nullable=True),
    sa.Column('edit_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incoming_letter_id'], ['letters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ghost_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('off', 'draft', 'auto', name='ghostmode'), nullable=False),
    sa.Column('correspondent_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_drafts_approved', sa.Integer(), nullable=False),
    sa.Column('send_as_written_count', sa.Integer(), nullable=False),
    sa.Column('auto_consent_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ghost_settings')
    op.drop_table('ghost_drafts')
    op.drop_index(op.f('ix_letters_to_address'), table_name='letters')
    op.drop_table('letters')
    op.drop_index(op.f('ix_guestbook_entries_echo_address'), table_name='guestbook_entries')
    op.drop_table('guestbook_entries')
    # ### end Alembic commands ###
